convert_parameters:
  delay: 6.0
  lookback: 2.0
  lookout: 2.0
  normalize: true
  smoothing: Gaussian
  vec_dim: 300
data:
  all_text_embs_dir: ./data/fasttext_outputs
  dataset_name: potter
  dict_dir: ./data/dicts
  fmri_dir: /home/kfb818/projects/datasets/fmri-sohmm/fmri/data
  fmri_sentences_path: ./data/harry_potter_sentences_pure.txt
  num_folds: 4
  num_subjects: 8
  word_decontextualized_embs_dir: ./data/LM_decontext_embs
  word_level_fmri_rep_dir: ./data/word_level_fmri
expdir:
  expname: hp_fasttext
model:
  model_alias: ft
  model_name: fasttext
  model_type: LM
  pretrained_model: google/bert_uncased_L-2_H-128_A-2
muse_parameters:
  cuda: true
  dico_build: S2T&T2S
  dico_eval: ./data/dicts
  dico_max_rank: 10000
  dico_max_size: 0
  dico_method: csls_knn_100
  dico_min_size: 0
  dico_threshold: 0
  dico_train: ./data/dicts
  emb_dim: 300
  exp_id: ''
  exp_name: hp_fasttext
  exp_path: ''
  export: ''
  load_optim: false
  max_vocab: 200000
  n_refinement: 0
  normalize_embeddings: center
  seed: -1
  src_emb: ./data/word_level_fmri
  src_lang: brain_8
  tgt_emb: ./data/fasttext_outputs/fasttext_potter_300.txt
  tgt_lang: fasttext
  verbose: 2
