expdir:
  expname: seg_enc
data:
  output_dir: './data/outputs/VM_out'
  reduced_output_dir: ./data/outputs/VM_out_reduced
  reduced_emb_dir: ./data/embeddings/VM_emb_reduced
  emb_dir: './data/embeddings/VM_emb'
  image_dir: '~/Dir/datasets/imagenet_21k_small'
  image_id2words: './data/image_ids_wiki_using.txt'
  per_object_embs_path: ./data/embeddings/seg_images_embeddings # Directory to save the embeddings of per image/word
model:
  model_type: VM
  model_alias: segformer
  pretrained_model: nvidia/segformer-b0-finetuned-ade-512-512
  model_name: segformer-b0-finetuned-ade-512-512
  n_components: 2 # dimension size of embeddings
  need_per_object_embs: True # if you need to save the embeddings of every image/word